### ISSUE TITLE
Multi-GPU Support (Docker)

### ISSUE THREAD

**Issue by chutson92** [skier233/nsfw_ai_model_server#10]
Is there multi-gpu support in the current iteration of the platform? 

Running this on docker within UnRAID.

**Comment by skier233** [comment]
So models are customizable and you can choose a device (such as gpu, cpu, or a gpu device id). So in theory you could run multiple different models on different GPU's. That being said I have no way to test such a theoretical scenario to know if it would work or there would be issues and there isn't currently any support for a setup that tries to evenly balance work across multiple GPU's.

**Comment by chutson92** [comment]
Thank you!  Good to know, and if there ever comes a time that this could be implemented, I'd be happy to do some testing on my end.

**Comment by skier233** [comment]
Yea I don't have a setup with multiple gpus so I'd definitely have to heavily rely on others to be able to test this.

**Comment by chutson92** [comment]
I'd also be happy to provide some basic gpu's (entry-level quadro's of the appropriate age) to test with if it made things easier.
