### ISSUE TITLE
How to run multiple models/pipelines at once?

### ISSUE THREAD

**Issue by chutson92** [skier233/nsfw_ai_model_server#11]
I see this listed in the documentation, but not how to actually make those updates. 

I'm assuming I would just add more than two active pipelines in the top line?

active_pipelines: ["video_pipeline_vivid_galaxy", "image_pipeline_vivid_galaxy"]
default_image_pipeline: "image_pipeline_vivid_galaxy"
default_video_pipeline: "video_pipeline_vivid_galaxy"

**Comment by chutson92** [comment]
For example, using the gentler river (sexual actions) model along with the iconic sky (body parts) model.  

Essentially trying to get the most tags possible out of the workflow if that makes sense.

**Comment by chutson92** [comment]
I do not have that, and I can't find it anywhere on GitHub as well.

**Comment by skier233** [comment]
That pipeline yaml is included with the iconic sky (body parts) model download

**Comment by chutson92** [comment]
Oh got it!  Thank you!  That makes sense.  Apologies for blowing this up, figure it might be nice info for other looking to leverage this project.
