### ISSUE TITLE
Remove '_AI' from added tags

### ISSUE THREAD

**Issue by chutson92** [skier233/nsfw_ai_model_server#12]
Is there anyway to remove the '_AI' ending for the tags added by AI?  It creates 'duplicate-ish' tags.  

Currently using the 'gentler river' model. 

I could add the normal tags, and remove the 'AI' tags after the fact, but if this is running ongoing, seems like a lot of effort. 

<img width="446" alt="Screenshot 2024-09-11 at 3 17 12 PM" src="https://github.com/user-attachments/assets/2d9ba51e-4af0-4090-a590-42b39381ebf9">

**Comment by skier233** [comment]
Good question! So the reason that prefix is on there to begin with is to make it clear that the tags are generated from the AI and to be able to distinguish AI generated tags from tags manually labeled or acquired elsewhere. My usual recommendation is you can make the "_AI" tags a child of existing equivalent tags and then if you search one of the normal tags then the AI ones would also show up. So you could for example manaully make Blowjob_AI a child of "Blowjob" and then if you search for "Blowjob" in the UI, stash would also find the Blowjob_AI tags. The name of the AI tags is also customizable as well if you wanted to remove the _AI suffix entirely that can be done in the tagmappings.csv file in the ai_tagger stash plugin folder. More info on that file here:https://github.com/skier233/nsfw_ai_model_server/wiki/Stash-Plugin-Guide#customizing-the-plugin-optional

**Comment by chutson92** [comment]
That's a great way to go about it with the child-tag. 

But nonetheless, great information that you can change it if wanted.
