### ISSUE TITLE
Error: Invalid license - Kubernetes

### ISSUE THREAD

**Issue by 8-cm** [skier233/nsfw_ai_model_server#15]
Hi - I am getting an error (image attachment).

I have followed the guide for manual installation (both free tier and Patreon tier), it works without an issue. When I replicate the setup in kubernetes, it works without issue only for Free tier. On Patreon tier that needs the license which I download from url or "reuse" from manual installation.

![image](https://github.com/user-attachments/assets/84424c1c-9cad-4be1-bf88-8dbd8cccb6c9)

Basically my setup is this:

```
              apt update -y && \
              apt upgrade -y && \
              apt install -y git python3 python3-pip unzip nix wget && \
              nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs && \
              nix-channel --update && \
              export PATH=$PATH:$HOME/.nix-profile/bin && \
              nix-env -iA nixpkgs.megacmd && \
              mkdir -p ~/miniconda3 && \
              wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh && \
              bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3 && \
              rm -rf ~/miniconda3/miniconda.sh && \
              source ~/miniconda3/bin/activate && \
              conda init --all && \
              mkdir /root/ai-data/ai-server && \
              mkdir /root/ai-data/ai-model && \
              wget https://github.com/skier233/nsfw_ai_model_server/releases/download/1.3.7/nsfw_ai_model_server.zip && \
              #free tier
              #mega-get https://mega.nz/file/BaRVEAQT#vseslzl7dAG-WQovgRteZsA02HteHJ3J-bR4MMlqJyE && \
              #patreon tier
              mega-get https://mega.nz/file/kXwUGY6Q#rFiuKQJMxmY6tSKecfBThM7F9uMcuemEnBy2VQFNFKc && \
              unzip ./nsfw_ai_model_server.zip -d /root/ai-data/ai-server && \
              unzip ./gentler_river_CPU.zip -d /root/ai-data/ai-model && \
              cp -r /root/ai-data/ai-model/config/* /root/ai-data/ai-server/config/ && \
              cp -r /root/ai-data/ai-model/models/* /root/ai-data/ai-server/models/ && \
              cp /root/ai-data/licenseV1.0.lic /root/ai-data/ai-server/models/licenseV1.0.lic && \
              cd /root/ai-data/ai-server && source ./install.sh
```

I would love appreciate your help for investigating the issue.
Thank you kindly.

P.S.: I am getting same error even in the LXC containers (just to mention).

**Comment by skier233** [comment]
What's your usecase for running in Kubernetes? I'd struggle to think of a usecase for it.

As for the licenses, you won't be able to reuse a license that you generated from when running natively, you'd need to get a new license when running with docker.

**Comment by 8-cm** [comment]
> What's your usecase for running in Kubernetes? I'd struggle to think of a usecase for it.
> 
> 
> 
> As for the licenses, you won't be able to reuse a license that you generated from when running natively, you'd need to get a new license when running with docker. Here's instructions on getting docker setup and working with the ai server: https://github.com/skier233/nsfw_ai_model_server/wiki/Installation-Instructions-(Docker)

My main usecase is high availability (or at least quick migration if HA is not supported) of all my selfhosted apps. Also its my learning lab and working with kubernetes is my job too.


And basically I do not have access to docker, because for me it is step back for my learning curve.

Also kubernetes as of today is usually does not use docker as its runtime (but that is another story).

**Comment by skier233** [comment]
Generally for high availability on a single machine, docker compose will be a much better and lighter setup than trying to run kubernetes. I'm not sure if kubernetes will work with the AI Server though due to how the licensing works.

**Comment by 8-cm** [comment]
I understand that Docker Compose can be a lighter setup for high availability on a single machine, but my primary use case is working across multiple physical nodes. Kubernetes offers significant advantages for this setup, especially in terms of high availability, workload migration, and resource management across nodes.

Also, I don’t have just a single machine—I have more of them. Kubernetes supports many more advantages over Docker, even when run on a single node. For instance, Kubernetes allows me to pin projects to specific nodes, create multiple pods, and load balance them—even if the application doesn’t natively support high availability or multiple replicas. This flexibility makes it an ideal choice for my setup.

Additionally, Kubernetes aligns well with my current learning goals and professional requirements, as I work with it regularly. While Docker Compose is valuable, Kubernetes gives me more flexibility and control in a multi-node environment.

BTW if you’re interested, I can help create a Docker image! I noticed from other issues that this has come up, and I’m experienced in building images, so feel free to reach out if that would be helpful.

> I'm not sure if kubernetes will work with the AI Server though due to how the licensing works.
Could you please explain how the licensing mechanism works? Specifically, I’m trying to understand what the "**Source error**" means and how the license verification process is handled. I suspect that the server might be checking host-specific details to validate the license, and if I can provide the necessary capabilities or host-based specifics to my Kubernetes pod, it might resolve the issue.

My background isn’t primarily in Python, so I’d appreciate any insights on what specifics or dependencies might be required for this setup. If I can understand more about what the AI Server is looking for, I can better configure my pod environment to meet those requirements.

Thanks again for your assistance!

**Comment by skier233** [comment]
Yea I get the kubernetes benefits in a multi machine system (I also use kubernetes at work). I'm not sure if such a system lines up well with the design goals of this project though (intended to be run locally for personal use). The licensing mechanism requests a license on the first run on a machine or container and then stores a license which will work in the future for that container/machine. The nature of kubernetes where it can constantly spin up new pods is going to probably be a problem as there wouldn't really be a mechanism to acquire licenses for each new pod.

Also for this project I'm not sure high availability even makes that much sense. If the server were to go down then the only effect would be that you'd have to restart the server to process more items. Also at this point the only times when I see the AI Server crash are GPU memory issues (of which in these cases even in kubernetes it would likely struggle). 

As for building a docker image, yea if you want to build a publish one that could be useful to simplify the docker installation process.

**Comment by 8-cm** [comment]
> The nature of kubernetes where it can constantly spin up new pods is going to probably be a problem as there wouldn't really be a mechanism to acquire licenses for each new pod.

Well would be nice different licensing model maybe then, or some sort of shared license file based on hosts that pods are running on (some kind of prepopulation then).
>(intended to be run locally for personal use).

GPU support for Kubernetes is not problem, so I guess it will be matter of time that Kubernetes support would be demanded - if the project would be successful/noticed by relevant companies.

>(intended to be run locally for personal use)

I guess that this is majority of your customers (based on majority of your LICENSE text), however you are also writing that you are open for enterprise licensing and that you should be contacted in that matter.   

I can wait or even help. But I would need info how the license mechanism works (technical one).
Do not get me wrong, I am not trying to "hack it". I just want to add support for Kubernetes (especially when the free version works there fantastically).

**Comment by skier233** [comment]
Enterprise support uses a different system. I'm not sure that a secure licensing system would even exist that could properly support kubernetes while still being secure within the confines of the current system using patreon. That's the inherent problem with trying to support kubernetes: 

- Supporting it would basically insecure the whole system
- The demand for it is basically zero

In your case if you have multiple machines with GPU's on them you could try having a native AI server (or standard docker) running on each and try using a load balancer to distribute the traffic but nothing in the AI Server code in this repo is designed around balancing load among nodes so it's hard to say how well such a setup may or may not work.

**Comment by skier233** [comment]
hmm. What do you mean by that *must allow click*
I'm not sure if patreon supports headless login. If it did then that would probably be a way that kubernetes could be supported

**Comment by 8-cm** [comment]
If I use manual approach the browser opens and even if you are logged in Patreon, there is confirmation button to allow access for the account info - when you click on allow after that the license is downloaded. It works the same if you copy the generated link for the firs time launch in docker.

<img width="423" alt="image" src="https://github.com/user-attachments/assets/19bf9987-fb63-43c4-b2da-bc40b629a17f">

**Comment by skier233** [comment]
That comes from patreon's api directly. I don't think I would have control to make it automatically allow.

**Comment by 8-cm** [comment]
Maybe some sort of pre allow step from the client side would be solution ? something like in google platforms secure app password

**Comment by skier233** [comment]
I'm not sure if something like that could work but you can feel free to try it. If you find a way to get some kind of headless login working I'd be happy to add code in for it as an option.
