### ISSUE TITLE
Feature Request: Stash plugin - Implement a "Tag Negative Matcher"

### ISSUE THREAD

**Issue by 8-cm** [skier233/nsfw_ai_model_server#16]
**Feature Request: "TagNegative Matcher" for Stash Plugin**

**Description:**  
Implement a "TagNegative Matcher" feature for the Stash plugin, which would automatically exclude videos from further processing if specific tag(s) are present.

**Purpose:**  
This feature would enable users to efficiently parse their entire video library without needing to manually tag each video beforehand. The "TagNegative Matcher" would prevent re-processing of already parsed videos by excluding items having certain tags (like AI_Tagged), streamlining the workflow and reducing redundant processing. Additionally, it would complement the plugin's existing tagging functionality, ensuring that once a video is processed and tagged, it’s automatically excluded from further processing rounds.

**Benefit:**  
This feature would save time and effort by automating the exclusion of already parsed content, allowing users to focus on unprocessed videos without manual intervention.

P.S.: I am not saying, it should be the default, but would be nice option.

**Comment by skier233** [comment]
This feature already exists. After a video is tagged once, if you process that video again, it will use stored results rather than running it from the AI again (unless the settings have changed in such a way that require it to run through the AI again)

**Comment by 8-cm** [comment]
> This feature already exists. After a video is tagged once, if you process that video again, it will use stored results rather than running it from the AI again (unless the settings have changed in such a way that require it to run through the AI again).
> 
> See https://github.com/skier233/nsfw_ai_model_server/wiki/Stash-Plugin-Guide#updating-previously-tagged-scenes

@skier233 
Well my problem is that there I condition "After a video is tagged once". What I need is that I need to process all videos without certain tag (even for the first time). Example is to target all videos without tags at all for the firs time .

**Comment by skier233** [comment]
If you want to process all videos without a certain tag then it sounds like using a filter in stash to select all videos without those particular tags you're interested in and adding AI_TagMe to those videos is probably the best way to do it.

**Comment by 8-cm** [comment]
But doesn't it mean that I need to open each video and assign the tag in manual way? (Maybe I am missing something, but I have not found the way to do that.)

**Comment by skier233** [comment]
No. You could just use the filters at the top and filter all videos that *don't* have a certain tag, then select all of them and add the AI_TagMe tag to them all. Nothing should ever require opening videos one by one.
