### ISSUE TITLE
Feature Request: ZLUDA

### ISSUE THREAD

**Issue by iamagithublearner** [skier233/nsfw_ai_model_server#17]
Support for ZLUDA , to support AMD GPUs.
ZLUDA is a drop-in replacement for CUDA on non-NVIDIA GPU
https://github.com/vosen/ZLUDA

**Comment by skier233** [comment]
This isn't up to me. It's not supported by pytorch so its out of my control: https://github.com/pytorch/pytorch/issues/129019

**Comment by sorasoras** [comment]
> This isn't up to me. It's not supported by pytorch so its out of my control: https://github.com/pytorch/pytorch/issues/129019

it should work with Pytorch 2.3/cuda11.8
