### ISSUE TITLE
How to run in docker

### ISSUE THREAD

**Issue by binarygeek119** [skier233/nsfw_ai_model_server#2]
I need help figuring out how to run in docker on unraid.

**Comment by skier233** [comment]
Docker is not currently supported

**Comment by skier233** [comment]
@binarygeek119 docker is now supported in release 1.3.3. Installation instructions can be found in the readme.

**Comment by binarygeek119** [comment]
You need to edit this line

&& rm -rf /var/lib/apt/lists/*

To this 
&& rm -rf "/var/lib/apt/lists/*"

Else it won't build

**Comment by skier233** [comment]
Are you sure? It built fine on my end. Maybe it’s a difference in behavior in different docker versions or something?

**Comment by binarygeek119** [comment]
Sorry was the time on my server it was off
