### ISSUE TITLE
E: Unable to locate package python3.12-distutils

### ISSUE THREAD

**Issue by MachineGalaxy** [skier233/nsfw_ai_model_server#20]
Hi, Im trying to build the Docker image.

After running the build command it errors out with the error
```
E: Unable to locate package python3.12-distutils
E: Couldn't find any package by glob 'python3.12-distutils'
E: Couldn't find any package by regex 'python3.12-distutils'
```
This is due to distutils having being deprecated in Python 3.12. The fix was to remove python3.12-distutils from the dockerfile and add setuptools to the requirements.txt

**Comment by skier233** [comment]
Good find! I pushed a commit and updated the current release with the change to the dockerfile
