### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by binarygeek119** [skier233/nsfw_ai_model_server#3]
im getting this error when i try to build.
```
Step 9/13 : COPY dist/ai_processing-0.0.0-cp311-cp311-linux_x86_64.whl /tmp/
COPY failed: file not found in build context or excluded by .dockerignore: stat dist/ai_processing-0.0.0-cp311-cp311-linux_x86_64.whl: file does not exist
```

**Comment by skier233** [comment]
Did you run the build command from the folder where you downloaded the ai server?

**Comment by binarygeek119** [comment]
yes. i `git clone https://github.com/skier233/nsfw_ai_model_server.git` then `cd  nsfw_ai_model_server` then `docker build -t ai_model_server .
`

**Comment by skier233** [comment]
@binarygeek119 That's your issue. You need to download a release not git clone the repo.

**Comment by binarygeek119** [comment]
thanks will do.
