### ISSUE TITLE
ModuleNotFoundError: No module named 'ai_processing'

### ISSUE THREAD

**Issue by cjb900** [skier233/nsfw_ai_model_server#5]
Hi i'v been trying to install this on a Windows 11 system and Ubuntu server and when i go to run `installer.ps1` or `install.sh` i get the below errors and i can't seem to fins anything online on how to fix this as there does not seem to be any pip package called `ai_processsing`. I did install the requirements i the requirements and made sure conda was setup on both systems 

Windows 11 
PS C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)> ./install.ps1

CondaValueError: prefix already exists: C:\Users\cjb900\miniconda3\envs\ai_model_server

Traceback (most recent call last):
  File "C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\server.py", line 2, in <module>
    from lib.server.server_manager import app, port
  File "C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\lib\server\server_manager.py", line 12, in <module>
    from lib.pipeline.pipeline_manager import PipelineManager
  File "C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\lib\pipeline\pipeline_manager.py", line 5, in <module>
    from lib.pipeline.pipeline import Pipeline
  File "C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\lib\pipeline\pipeline.py", line 2, in <module>
    from lib.model.ai_model import AIModel
  File "C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\lib\model\ai_model.py", line 4, in <module>
    from ai_processing import ModelRunner
ModuleNotFoundError: No module named 'ai_processing'

Ubuntu server 

cjb900@cjb900:~/nsfw_ai_model_server$ ./install.sh
Retrieving notices: ...working... done

CondaValueError: prefix already exists: /home/cjb900/.conda/envs/ai_model_server

CondaError: Run 'conda init' before 'conda activate'

Traceback (most recent call last):
  File "/home/cjb900/nsfw_ai_model_server/server.py", line 2, in <module>
    from lib.server.server_manager import app, port
  File "/home/cjb900/nsfw_ai_model_server/lib/server/server_manager.py", line 12, in <module>
    from lib.pipeline.pipeline_manager import PipelineManager
  File "/home/cjb900/nsfw_ai_model_server/lib/pipeline/pipeline_manager.py", line 5, in <module>
    from lib.pipeline.pipeline import Pipeline
  File "/home/cjb900/nsfw_ai_model_server/lib/pipeline/pipeline.py", line 2, in <module>
    from lib.model.ai_model import AIModel
  File "/home/cjb900/nsfw_ai_model_server/lib/model/ai_model.py", line 4, in <module>
    from ai_processing import ModelRunner
ModuleNotFoundError: No module named 'ai_processing'

**Comment by skier233** [comment]
Did you download the latest release? If you just cloned the repository then that would explain the issue as those files are only included in a release.

**Comment by cjb900** [comment]
yes i downloaded the latest release on both systems and get the same results

**Comment by skier233** [comment]
> yes i downloaded the latest release on both systems and get the same results

try doing:
`conda remove -n ai_model_server --all`
`./install.ps1`

**Comment by cjb900** [comment]
Ya running that conda remove command and re-running `./install.ps1` i get the same thing 

PS C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)> conda remove -n ai_model_server --all

Remove all packages in environment C:\Users\cjb900\miniconda3\envs\ai_model_server:


## Package Plan ##

  environment location: C:\Users\cjb900\miniconda3\envs\ai_model_server


The following packages will be REMOVED:

  blas-1.0-mkl
  brotli-python-1.0.9-py311hd77b12b_8
  bzip2-1.0.8-h2bbff1b_6
  ca-certificates-2024.3.11-haa95532_0
  cccl-2.3.2-h47f531a_0
  certifi-2024.7.4-py311haa95532_0
  charset-normalizer-2.0.4-pyhd3eb1b0_0
  cuda-cccl-12.4.127-haa95532_2
  cuda-cccl_win-64-12.4.127-haa95532_2
  cuda-cudart-12.1.105-0
  cuda-cudart-dev-12.1.105-0
  cuda-cupti-12.1.105-0
  cuda-libraries-12.1.0-0
  cuda-libraries-dev-12.1.0-0
  cuda-nvrtc-12.1.105-0
  cuda-nvrtc-dev-12.1.105-0
  cuda-nvtx-12.1.105-0
  cuda-opencl-12.4.127-hd77b12b_0
  cuda-opencl-dev-12.4.127-hd77b12b_0
  cuda-profiler-api-12.4.127-haa95532_1
  cuda-runtime-12.1.0-0
  cuda-version-12.4-hbda6634_3
  filelock-3.13.1-py311haa95532_0
  freetype-2.12.1-ha860e81_0
  gmpy2-2.1.2-py311h7f96b67_0
  idna-3.7-py311haa95532_0
  intel-openmp-2021.4.0-haa95532_3556
  jinja2-3.1.4-py311haa95532_0
  jpeg-9e-h2bbff1b_1
  khronos-opencl-icd-loader-2024.05.08-h8cc25b3_0
  lcms2-2.12-h83e58a3_0
  lerc-3.0-hd77b12b_0
  libcublas-12.1.0.26-0
  libcublas-dev-12.1.0.26-0
  libcufft-11.0.2.4-0
  libcufft-dev-11.0.2.4-0
  libcurand-10.3.5.147-hd77b12b_1
  libcurand-dev-10.3.5.147-hd77b12b_1
  libcusolver-11.4.4.55-0
  libcusolver-dev-11.4.4.55-0
  libcusparse-12.0.2.55-0
  libcusparse-dev-12.0.2.55-0
  libdeflate-1.17-h2bbff1b_1
  libffi-3.4.4-hd77b12b_1
  libjpeg-turbo-2.0.0-h196d8e1_0
  libnpp-12.0.2.50-0
  libnpp-dev-12.0.2.50-0
  libnvjitlink-12.1.105-0
  libnvjitlink-dev-12.1.105-0
  libnvjpeg-12.1.1.14-0
  libnvjpeg-dev-12.1.1.14-0
  libpng-1.6.39-h8cc25b3_0
  libtiff-4.5.1-hd77b12b_0
  libuv-1.44.2-h2bbff1b_0
  libwebp-base-1.3.2-h2bbff1b_0
  lz4-c-1.9.4-h2bbff1b_1
  markupsafe-2.1.3-py311h2bbff1b_0
  mkl-2021.4.0-haa95532_640
  mkl-service-2.4.0-py311h2bbff1b_0
  mkl_fft-1.3.1-py311h743a336_0
  mkl_random-1.2.2-py311heda8569_0
  mpc-1.1.0-h7edee0f_1
  mpfr-4.0.2-h62dcd97_1
  mpir-3.0.0-hec2e145_1
  mpmath-1.3.0-py311haa95532_0
  networkx-3.3-py311haa95532_0
  numpy-1.24.3-py311ha6a8073_0
  numpy-base-1.24.3-py311h877bb12_0
  openjpeg-2.4.0-h4afccc4_1
  openssl-3.0.14-h827c3e9_0
  pillow-10.3.0-py311h2bbff1b_0
  pip-24.0-py311haa95532_0
  pysocks-1.7.1-py311haa95532_0
  python-3.11.9-he1021f5_0
  pytorch-2.3.1-py3.11_cuda12.1_cudnn8_0
  pytorch-cuda-12.1-hde6ce7c_5
  pytorch-mutex-1.0-cuda
  pyyaml-6.0.1-py311h2bbff1b_0
  requests-2.32.2-py311haa95532_0
  setuptools-69.5.1-py311haa95532_0
  six-1.16.0-pyhd3eb1b0_1
  sqlite-3.45.3-h2bbff1b_0
  sympy-1.12-py311haa95532_0
  tk-8.6.14-h0416ee5_0
  torchvision-0.18.1-py311_cu121
  typing_extensions-4.11.0-py311haa95532_0
  tzdata-2024a-h04d1e81_0
  urllib3-2.2.2-py311haa95532_0
  vc-14.2-h2eaa2aa_4
  vs2015_runtime-14.29.30133-h43f2093_4
  wheel-0.43.0-py311haa95532_0
  win_inet_pton-1.1.0-py311haa95532_0
  xz-5.4.6-h8cc25b3_1
  yaml-0.2.5-he774522_0
  zlib-1.2.13-h8cc25b3_1
  zstd-1.5.5-hd43e919_2


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Everything found within the environment (C:\Users\cjb900\miniconda3\envs\ai_model_server), including any conda environment configurations and any non-conda files, will be deleted. Do you wish to continue?
 (y/[n])? y

PS C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)> ./install.ps1
Channels:
 - defaults
 - pytorch
 - nvidia
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: | Ran pip subprocess with arguments:
['C:\\Users\\cjb900\\miniconda3\\envs\\ai_model_server\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\cj]
Pip subprocess output:
Processing c:\users\cjb900\downloads\nsfw_ai_model_server2 (2)\dist\ai_processing-0.0.0-cp311-cp311-win_amd64.whl (from)
Collecting decord (from -r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.requirements.txt (line)
  Using cached decord-0.6.0-py3-none-win_amd64.whl.metadata (422 bytes)
Collecting fastapi==0.111.0 (from -r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.requirements)
  Using cached fastapi-0.111.0-py3-none-any.whl.metadata (25 kB)
Collecting pycryptodomex==3.20.0 (from -r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.require)
  Using cached pycryptodomex-3.20.0-cp35-abi3-win_amd64.whl.metadata (3.4 kB)
Collecting uvicorn==0.29.0 (from -r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.requirements.)
  Using cached uvicorn-0.29.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: requests in c:\users\cjb900\miniconda3\envs\ai_model_server\lib\site-packages (from -r C)
Collecting requests (from -r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.requirements.txt (li)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting aiohttp (from -r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.requirements.txt (lin)
  Using cached aiohttp-3.9.5-cp311-cp311-win_amd64.whl.metadata (7.7 kB)
Collecting colorlog (from -r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.requirements.txt (li)
  Using cached colorlog-6.8.2-py3-none-any.whl.metadata (10 kB)
Collecting psutil (from -r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.requirements.txt (line)
  Using cached psutil-6.0.0-cp37-abi3-win_amd64.whl.metadata (22 kB)
Collecting wmi (from -r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.requirements.txt (line 10)
  Using cached WMI-1.5.1-py2.py3-none-any.whl.metadata (3.6 kB)
Collecting starlette<0.38.0,>=0.37.2 (from fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\con)
  Using cached starlette-0.37.2-py3-none-any.whl.metadata (5.9 kB)
Collecting pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 (from fastapi==0.111.0->-r C:\Users\cjb900\Down)
  Using cached pydantic-2.8.2-py3-none-any.whl.metadata (125 kB)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\cjb900\miniconda3\envs\ai_model_server\lib\site-pac)
Collecting fastapi-cli>=0.0.2 (from fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.t)
  Using cached fastapi_cli-0.0.4-py3-none-any.whl.metadata (7.0 kB)
Collecting httpx>=0.23.0 (from fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354e)
  Using cached httpx-0.27.0-py3-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: jinja2>=2.11.2 in c:\users\cjb900\miniconda3\envs\ai_model_server\lib\site-packages (fro)
Collecting python-multipart>=0.0.7 (from fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\conda)
  Using cached python_multipart-0.0.9-py3-none-any.whl.metadata (2.5 kB)
Collecting ujson!=4.0.2,!=4.1.0,!=4.2.0,!=4.3.0,!=5.0.0,!=5.1.0,>=4.0.1 (from fastapi==0.111.0->-r C:\Users\cjb900\Down)
  Using cached ujson-5.10.0-cp311-cp311-win_amd64.whl.metadata (9.5 kB)
Collecting orjson>=3.2.1 (from fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354e)
  Using cached orjson-3.10.6-cp311-none-win_amd64.whl.metadata (51 kB)
Collecting email_validator>=2.0.0 (from fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condae)
  Using cached email_validator-2.2.0-py3-none-any.whl.metadata (25 kB)
Collecting click>=7.0 (from uvicorn==0.29.0->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.r)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting h11>=0.8 (from uvicorn==0.29.0->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.req)
  Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\cjb900\miniconda3\envs\ai_model_server\lib\site-packages (from)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\cjb900\miniconda3\envs\ai_model_server\lib\site-pac)
Requirement already satisfied: idna<4,>=2.5 in c:\users\cjb900\miniconda3\envs\ai_model_server\lib\site-packages (from )
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\cjb900\miniconda3\envs\ai_model_server\lib\site-packages )
Requirement already satisfied: certifi>=2017.4.17 in c:\users\cjb900\miniconda3\envs\ai_model_server\lib\site-packages )
Collecting aiosignal>=1.1.2 (from aiohttp->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.req)
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting attrs>=17.3.0 (from aiohttp->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.requir)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting frozenlist>=1.1.1 (from aiohttp->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.re)
  Using cached frozenlist-1.4.1-cp311-cp311-win_amd64.whl.metadata (12 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.)
  Using cached multidict-6.0.5-cp311-cp311-win_amd64.whl.metadata (4.3 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.requi)
  Using cached yarl-1.9.4-cp311-cp311-win_amd64.whl.metadata (32 kB)
Collecting colorama (from colorlog->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.requiremen)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting pywin32 (from wmi->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv.tt354ecs.requirements.txt)
  Using cached pywin32-306-cp311-cp311-win_amd64.whl.metadata (6.5 kB)
Collecting dnspython>=2.0.0 (from email_validator>=2.0.0->fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_model_)
  Using cached dnspython-2.6.1-py3-none-any.whl.metadata (5.8 kB)
Collecting typer>=0.12.3 (from fastapi-cli>=0.0.2->fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2)
  Using cached typer-0.12.3-py3-none-any.whl.metadata (15 kB)
Collecting anyio (from httpx>=0.23.0->fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condaenv)
  Using cached anyio-4.4.0-py3-none-any.whl.metadata (4.6 kB)
Collecting httpcore==1.* (from httpx>=0.23.0->fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\)
  Using cached httpcore-1.0.5-py3-none-any.whl.metadata (20 kB)
Collecting sniffio (from httpx>=0.23.0->fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\condae)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\cjb900\miniconda3\envs\ai_model_server\lib\site-packages (fr)
Collecting annotated-types>=0.4.0 (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi==0.111.0-)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.20.1 (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi==0.111.0->)
  Using cached pydantic_core-2.20.1-cp311-none-win_amd64.whl.metadata (6.7 kB)
Collecting httptools>=0.5.0 (from uvicorn[standard]>=0.12.0->fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_mod)
  Using cached httptools-0.6.1-cp311-cp311-win_amd64.whl.metadata (3.7 kB)
Collecting python-dotenv>=0.13 (from uvicorn[standard]>=0.12.0->fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_)
  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: pyyaml>=5.1 in c:\users\cjb900\miniconda3\envs\ai_model_server\lib\site-packages (from u)
Collecting watchfiles>=0.13 (from uvicorn[standard]>=0.12.0->fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_mod)
  Using cached watchfiles-0.22.0-cp311-none-win_amd64.whl.metadata (5.0 kB)
Collecting websockets>=10.4 (from uvicorn[standard]>=0.12.0->fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_ai_mod)
  Using cached websockets-12.0-cp311-cp311-win_amd64.whl.metadata (6.8 kB)
Collecting shellingham>=1.3.0 (from typer>=0.12.3->fastapi-cli>=0.0.2->fastapi==0.111.0->-r C:\Users\cjb900\Downloads\n)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=10.11.0 (from typer>=0.12.3->fastapi-cli>=0.0.2->fastapi==0.111.0->-r C:\Users\cjb900\Downloads\nsfw_a)
  Using cached rich-13.7.1-py3-none-any.whl.metadata (18 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi==0.111.0->-r C:\Users\)
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi==0.111.0->-r C:\User)
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi==0.111.0->)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached fastapi-0.111.0-py3-none-any.whl (91 kB)
Using cached pycryptodomex-3.20.0-cp35-abi3-win_amd64.whl (1.8 MB)
Using cached uvicorn-0.29.0-py3-none-any.whl (60 kB)
Using cached decord-0.6.0-py3-none-win_amd64.whl (24.7 MB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached aiohttp-3.9.5-cp311-cp311-win_amd64.whl (370 kB)
Using cached colorlog-6.8.2-py3-none-any.whl (11 kB)
Using cached psutil-6.0.0-cp37-abi3-win_amd64.whl (257 kB)
Using cached WMI-1.5.1-py2.py3-none-any.whl (28 kB)
Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached email_validator-2.2.0-py3-none-any.whl (33 kB)
Using cached fastapi_cli-0.0.4-py3-none-any.whl (9.5 kB)
Using cached frozenlist-1.4.1-cp311-cp311-win_amd64.whl (50 kB)
Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Using cached httpx-0.27.0-py3-none-any.whl (75 kB)
Using cached httpcore-1.0.5-py3-none-any.whl (77 kB)
Using cached multidict-6.0.5-cp311-cp311-win_amd64.whl (28 kB)
Using cached orjson-3.10.6-cp311-none-win_amd64.whl (136 kB)
Using cached pydantic-2.8.2-py3-none-any.whl (423 kB)
Using cached pydantic_core-2.20.1-cp311-none-win_amd64.whl (1.9 MB)
Using cached python_multipart-0.0.9-py3-none-any.whl (22 kB)
Using cached starlette-0.37.2-py3-none-any.whl (71 kB)
Using cached ujson-5.10.0-cp311-cp311-win_amd64.whl (42 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached yarl-1.9.4-cp311-cp311-win_amd64.whl (76 kB)
Using cached pywin32-306-cp311-cp311-win_amd64.whl (9.2 MB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached anyio-4.4.0-py3-none-any.whl (86 kB)
Using cached dnspython-2.6.1-py3-none-any.whl (307 kB)
Using cached httptools-0.6.1-cp311-cp311-win_amd64.whl (55 kB)
Using cached python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached typer-0.12.3-py3-none-any.whl (47 kB)
Using cached watchfiles-0.22.0-cp311-none-win_amd64.whl (281 kB)
Using cached websockets-12.0-cp311-cp311-win_amd64.whl (124 kB)
Using cached rich-13.7.1-py3-none-any.whl (240 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: pywin32, ai-processing, wmi, websockets, ujson, sniffio, shellingham, requests, python-mi
  Attempting uninstall: requests
    Found existing installation: requests 2.32.2
    Uninstalling requests-2.32.2:
      Successfully uninstalled requests-2.32.2
Successfully installed ai-processing-0.0.0 aiohttp-3.9.5 aiosignal-1.3.1 annotated-types-0.7.0 anyio-4.4.0 attrs-23.2.04

done
#
# To activate this environment, use
#
#     $ conda activate ai_model_server
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Traceback (most recent call last):
  File "C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\server.py", line 2, in <module>
    from lib.server.server_manager import app, port
  File "C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\lib\server\server_manager.py", line 12, in <module>
    from lib.pipeline.pipeline_manager import PipelineManager
  File "C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\lib\pipeline\pipeline_manager.py", line 5, in <module>
    from lib.pipeline.pipeline import Pipeline
  File "C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\lib\pipeline\pipeline.py", line 2, in <module>
    from lib.model.ai_model import AIModel
  File "C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)\lib\model\ai_model.py", line 4, in <module>
    from ai_processing import ModelRunner
ModuleNotFoundError: No module named 'ai_processing'
PS C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)>

**Comment by skier233** [comment]
it looks like its failing to activate the conda environment. Can you try `conda activate ai_model_server` and see what the response is?

**Comment by cjb900** [comment]
that didn't do anything but flash some screen for less than a second and gave no additional output

**Comment by skier233** [comment]
Ok, can you try: `conda env list`. I think something with your conda install might be messed up and this will confirm it if so.

**Comment by cjb900** [comment]
gives me this 

```PS C:\Users\cjb900\Downloads\nsfw_ai_model_server2 (2)> conda env list
# conda environments:
#
base                     C:\Users\cjb900\miniconda3
ai_model_server          C:\Users\cjb900\miniconda3\envs\ai_model_server```

**Comment by skier233** [comment]
> gives me this
> 
> ```postscript
> # conda environments:
> #
> base                     C:\Users\cjb900\miniconda3
> ai_model_server          C:\Users\cjb900\miniconda3\envs\ai_model_server```
> ```

Yea something is messed up with your conda install. if `conda activate ai_model_server` were working correctly then it should've activate the ai_model_server environment and you should see a * next to  ai_model_server indicating its the active environment. I'd try to reinstall conda.
