### ISSUE TITLE
Issue with the Plugin

### ISSUE THREAD

**Issue by installlooc** [skier233/nsfw_ai_model_server#6]
I've managed to get the requests coming through to the docker container as per the instructions and the videos appear to be processed correctly
`12:09:57|[INFO]:Processing video at path: /data/lydiagh0st/kSuFNyg5.mp4`
`INFO:     172.17.0.1:44442 - "POST /process_video/ HTTP/1.1" 200 OK`
`12:44:17|[INFO]:Preprocessed 421 frames in 95.40968155860901 seconds at an average of 0.22662632199194538 seconds per frame.`

However when posted back to Stash, I get the following error: 

> ERRO[2024-07-28 13:13:22] [Plugin / AI Tagger] Traceback (most recent call last): 
>ERRO[2024-07-28 13:13:22] [Plugin / AI Tagger] File "/root/.stash/plugins/community/ai_tagger/ai_tagger.py", line 257, in __tag_scene 
>ERRO[2024-07-28 13:13:22] [Plugin / AI Tagger] ai_video_result.to_json_file(ai_file_path) 
>ERRO[2024-07-28 13:13:22] [Plugin / AI Tagger] File "/root/.stash/plugins/community/ai_tagger/ai_video_result.py", line 130, in to_json_file 
>ERRO[2024-07-28 13:13:22] [Plugin / AI Tagger] with open(json_file, 'w') as f: 
>ERRO[2024-07-28 13:13:22] [Plugin / AI Tagger] ^^^^^^^^^^^^^^^^^^^^
>FileNotFoundError: [Errno 2] No such file or directory: 'data/lydiagh0st/kSuFNyg5.mp4.AI.json'

There's no trace of the .json file in the directory either and it comes back as AI_Errored. Any ideas?

**Comment by skier233** [comment]
> I've managed to get the requests coming through to the docker container as per the instructions and the videos appear to be processed correctly `12:09:57|[INFO]:Processing video at path: /data/lydiagh0st/kSuFNyg5.mp4` `INFO: 172.17.0.1:44442 - "POST /process_video/ HTTP/1.1" 200 OK` `12:44:17|[INFO]:Preprocessed 421 frames in 95.40968155860901 seconds at an average of 0.22662632199194538 seconds per frame.`
> 
> However when posted back to Stash, I get the following error:
> 
> > ERRO[2024-07-28 13:13:22] [Plugin / AI Tagger] Traceback (most recent call last):
> > ERRO[2024-07-28 13:13:22] [Plugin / AI Tagger] File "/root/.stash/plugins/community/ai_tagger/ai_tagger.py", line 257, in __tag_scene
> > ERRO[2024-07-28 13:13:22] [Plugin / AI Tagger] ai_video_result.to_json_file(ai_file_path)
> > ERRO[2024-07-28 13:13:22] [Plugin / AI Tagger] File "/root/.stash/plugins/community/ai_tagger/ai_video_result.py", line 130, in to_json_file
> > ERRO[2024-07-28 13:13:22] [Plugin / AI Tagger] with open(json_file, 'w') as f:
> > ERRO[2024-07-28 13:13:22] [Plugin / AI Tagger] ^^^^^^^^^^^^^^^^^^^^
> > FileNotFoundError: [Errno 2] No such file or directory: 'data/lydiagh0st/kSuFNyg5.mp4.AI.json'
> 
> There's no trace of the .json file in the directory either and it comes back as AI_Errored. Any ideas?

Can you confirm what the path should be for that video file? ie is there a path called:
`data/lydiagh0st/kSuFNyg5.mp4` within your stash docker container?

**Comment by installlooc** [comment]
Path is /data/lydiagh0st/kSuFNyg5.mp4 in the stash container, 

I used `path_mutation = {"data": "/data"}` in config.py to transform the path

**Comment by skier233** [comment]
Hmm. So are you saying that `data/lydiagh0st/kSuFNyg5.mp4` won't work within the stash container? If so that seems a bit odd to be the path stash is expecting. The path_mutation option only mutates the path sent to the ai server but not the paths used within the stash docker container to save files to so if the path to the video is `data/lydiagh0st/kSuFNyg5.mp4` then it'd expect that to be a valid path.

**Comment by installlooc** [comment]
The video plays fine in Stash, it's when it POSTs back to the plugin that it can't find it. The plugin is looking for the .json file as well, which doesn't exist in the bound folder

Model server was launched using this command, so should be able to write fine to the folder
`docker run --gpus all -p 8000:8000 -p 7483:7483 -v /mnt/n/StashTesting/data/:/data -v ./:/app ai_model_server`

**Comment by skier233** [comment]
The plugin isn’t trying to find that file; It’s trying to save the json to that file location but getting an issue trying to save to that path because it thinks that path is invalid. What does your library path in stash look like?

**Comment by installlooc** [comment]
Stash is setup with /data setup as a bind mount: `- /mnt/n/StashTesting/data:/data`

And the file info shows this as the path `file://data/lydiagh0st/-kSuFNyg5.mp4`

I threw a log into the ai_tagger.py to grab the scenePath value and it came out without the first initial /, for example: 
`log.error(scenePath)`
which returned:
`stash  | ERRO[2024-07-29 12:58:19] [Plugin / AI Tagger] data/lydiagh0st/VDGx3dga.mp4`

**Comment by skier233** [comment]
> Stash is setup with /data setup as a bind mount: `- /mnt/n/StashTesting/data:/data`
> 
> And the file info shows this as the path `file://data/lydiagh0st/-kSuFNyg5.mp4`
> 
> I threw a log into the ai_tagger.py to grab the scenePath value and it came out without the first initial /, for example: `log.error(scenePath)` which returned: `stash | ERRO[2024-07-29 12:58:19] [Plugin / AI Tagger] data/lydiagh0st/VDGx3dga.mp4`

This honestly seems like it could be a stash issue with how they're handling paths. Try this though and see if it works as a workaround for your case:
in the ai_tagger.py file, add this line right after this line 197:
Current line 197:
`ai_file_path = scenePath + ".AI.json"`
New Line added after 197:
`ai_file_path = ai_file_path.replace("data", "/data")`

**Comment by skier233** [comment]
Also if you get a chance can you tell me what the path is for the library folder stash is using to find the videos in that folder? I'm wondering if this comes about from an incorrect path in that library folder path.

**Comment by installlooc** [comment]
Yeah that change to the .py worked, looks like stash stores the path as data/ in the library, while also accepting /data as a valid library path

**Comment by skier233** [comment]
> Yeah that change to the .py worked, looks like stash stores the path as data/ in the library, while also accepting /data as a valid library path

Great that it unblocked you now. I guess the preferred thing to do is probably to update your library paths to use /data ideally in stash but that fix should work for now and if this issue comes up again I can look at adding logic on my side to mitigate this further.
