### ISSUE TITLE
Limit Memory Usage in Docker

### ISSUE THREAD

**Issue by chutson92** [skier233/nsfw_ai_model_server#9]
After much trial and error I finally got everything semi-running/working in UnRAID.  

With that being said, once I process any files, it uses all available system memory and locks up the system before completing processing of the file. 

Are there any ways around this, or do you have a reference on how much memory should be needed? 

Thanks!

**Comment by skier233** [comment]
Are you using a CPU or GPU model? And when you say it locks up memory do you mean the RAM or the GPU VRAM?

**Comment by chutson92** [comment]
Using the GPU model (vivid galaxy).  And I mean RAM, as no issues it if maxes out the GPU VRAM. 

Also, I was able to create a 16GB swap file on UnRAID and it seems to be using that now. Seeing 100% load and 84% memory utilization on my Quadro P620 (weak, I know). It has been running for about 20 minutes processing one file, does this seem normal? 

| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A     12234      G   /usr/libexec/Xorg                              11MiB |
|    0   N/A  N/A     46527      C   python3.12                                   1704MiB

**Comment by chutson92** [comment]
Essentially wanted to test if I could get everything working before I purchased additional (more powerful) hardware to throw at it.

**Comment by skier233** [comment]
It depends on the file you're processing. Is it a video or an image? And if its a video, what are the specs of the video (resolution, video duration). Also the GPU VRAM does matter as if it hits 100% then everything will get slowed way down. It might be a bit tricky not to max out the GPU VRAM on that GPU since it only has 2 GB VRAM.

**Comment by chutson92** [comment]
Ok the file actually processed, but I do see these errors and the video file in question now shows 'AI_Errored'.

24-09-10 16:07:46
Error   
[Plugin / AI Tagger] ai_video_result.to_json_file(ai_file_path)
2024-09-10 16:07:46
Error   
[Plugin / AI Tagger] AttributeError: 'AIVideoResult' object has no attribute 'model_dump_json'
2024-09-10 16:07:46
Error   
[Plugin / AI Tagger] File "/config/plugins/ai_tagger/ai_tagger.py", line 260, in __tag_scene
2024-09-10 16:07:46
Error   
[Plugin / AI Tagger] ^^^^^^^^^^^^^^^^^^^^
2024-09-10 16:07:46
Error   
[Plugin / AI Tagger] Failed to process video: 'AIVideoResult' object has no attribute 'model_dump_json'
2024-09-10 16:07:46
Error   
[Plugin / AI Tagger] Traceback (most recent call last):
2024-09-10 16:07:46
Error   
[Plugin / AI Tagger] File "/config/plugins/ai_tagger/ai_video_result.py", line 131, in to_json_file
2024-09-10 16:07:46
Error   
[Plugin / AI Tagger] f.write(self.model_dump_json(exclude_none=True))
2024-09-10 16:07:46
Error   
[Plugin / AI Tagger] e

Thank you for your patience here as I'm a complete newb to anything AI-related.

**Comment by skier233** [comment]
That error is coming from the stash plugin and is due to an out of date version of the pydantic python/pip dependency. I can help you fix that after I get back from the gym or if you’re familiar with pop and python you may be able to update that dependency which should fix it.

**Comment by skier233** [comment]
I can help out more with that if you didn't get it resolved. Basically what I'd do is go to wherever your python is installed that stash is using and then do pip install --upgrade pydantic  
If you have stash installed in docker as well let me know and the instructions will be a bit different.

**Comment by chutson92** [comment]
Hi yes, wasn't able to get it resolved myself.  Stash is running via docker in UnRAID as well.

**Comment by skier233** [comment]
Ok so when running stash in docker it gets a little more complicated due to how stash manages plugin dependencies. I have some information in discord describing how to get through this issue:
https://discord.com/channels/726822063821684867/1072593234083201135/1263541313303744574

Basically the idea is to create a python virtual env and install the plugin dependencies in it (you can do pip install -r requirements.txt in the virtual env). Then you’d like the path to that virtual env python as the python instance in the stash settings.

**Comment by chutson92** [comment]
Thank you for the timely updates on this.  Offered a quick resolution. 

Will definitely be supporting you on Patreon and trying the additional models!

Thanks again!

**Comment by skier233** [comment]
Glad you got it working!
